---
- name: Install cfssl
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl_1.5.0_linux_amd64
    dest: /usr/local/bin/cfssl
    mode: a+x
  register: results

- name: Install cfssljson
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssljson_1.5.0_linux_amd64
    dest: /usr/local/bin/cfssljson
    mode: a+x
  register: results
  
- name: Install cfssl-certinfo
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl-certinfo_1.5.0_linux_amd64
    dest: /usr/local/bin/cfssl-certinfo
    mode: a+x
  register: results

- name: Download kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl"
    dest: /kubectl
  register: results
  
- name: Install kubectl 
  ansible.builtin.command: install -o root -g root -m 0755 /kubectl /usr/local/bin/kubectl

